### ISSUE TITLE
Deployment workflow todos

### ISSUE THREAD

**Issue by striderhobbit** [striderhobbit/music-monk#1]
- [ ] Improve safety by using a token
- [ ] on: push and pull_request:

```yaml
name: Node.js Package deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```
